apiVersion: v1
kind: Pod
metadata:
  name: basic-pod
  labels:
    app: webapp
    type: frontend
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 8080
    
# kubectl create -f basic_pod.yaml
# kubectl get pods
# kubectl expose pod basic-pod --target-port=8080