# kubectl label nodes <node-name> proper:match
# kubecl get nodes --show-labels 
# kubecl get nodes -l ssd=true
# kubectl get DaemonSet
# kubectl describe DaemonSet <name>

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-selector
spec:
  selector:
    matchLabels:
      ssd: true
  template:
    metadata:
      name: ssd-pods
      labels:
        ssd: true
    spec:
      containers:
      - name: nginx
        image: nginx
      nodeSelector:
        ssd: true
