apiVersion: v1
kind: namespace
metadata:
    name: dev

---

apiVersion: v1
kind: Pod
metadata:
  name: devpod
  namespace: dev
spec:
  containers:
  - name: nginxy
    image: nginx

# kubectl create namespace dev
# kubectl get namespaces
# kubectl get pods --all-namespaces
# kubectl get pods -n dev
# kubectl create -f kuard.yaml -n dev