# The manifest file statefulset-demo.yaml creates a StatefulSet that includes a LoadBalancer service and three
# replicas of a Pod containing an nginx container and a volumeClaimTemplate for 30 gigabyte PVCs with the name
# hello-web-disk. The nginx containers mount the PVC called hello-web-disk at /var/www/html as in the previous
# task.

kind: Service
apiVersion: v1
metadata:
  name: statefulset-demo-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
  type: LoadBalancer
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-demo
spec:
  selector:
    matchLabels:
      app: MyApp
  serviceName: statefulset-demo-service
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: MyApp
    spec:
      containers:
      - name: stateful-set-container
        image: nginx
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: hello-web-disk
          mountPath: "/var/www/html"
  volumeClaimTemplates:
  - metadata:
      name: hello-web-disk
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 30Gi


# k get statefulset
# k describe statefulset statefulset-demo
# k get pods
# k get pvc
# kubectl describe pvc hello-web-disk-statefulset-demo-0